version: 1.0
security_key: 2ab90d39288c84986b155274176736c343f46894c94649ed101ff616894f36eb
database:
  driver: postgresql
  host: 127.0.0.1
  port: 5432
  username: root
  password: root
  timeout: 5s
  database: fsgql
  suffix: arxpr
  default_schema: public
