"""Updated created_at field

Revision ID: 015120712dbf
Revises: 2246e3550e81
Create Date: 2023-07-11 17:50:10.409482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015120712dbf'
down_revision = '2246e3550e81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_status_code_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'user_status', ['status_code'], ['code'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', schema='public', type_='foreignkey')
    op.create_foreign_key('user_status_code_fkey', 'user', 'user_status', ['status_code'], ['code'])
    # ### end Alembic commands ###
