"""made email field unique

Revision ID: c243403b3c94
Revises: a4f90ae69d8c
Create Date: 2023-07-12 14:03:54.951757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c243403b3c94'
down_revision = 'a4f90ae69d8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_public_user_email'), 'user', ['email'], unique=True, schema='public')
    op.drop_constraint('user_status_code_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'user_status', ['status_code'], ['code'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', schema='public', type_='foreignkey')
    op.create_foreign_key('user_status_code_fkey', 'user', 'user_status', ['status_code'], ['code'])
    op.drop_index(op.f('ix_public_user_email'), table_name='user', schema='public')
    # ### end Alembic commands ###
