"""Updated created_at field

Revision ID: e81fa127f60c
Revises: 015120712dbf
Create Date: 2023-07-11 17:53:53.180928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e81fa127f60c'
down_revision = '015120712dbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_status_code_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'user_status', ['status_code'], ['code'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', schema='public', type_='foreignkey')
    op.create_foreign_key('user_status_code_fkey', 'user', 'user_status', ['status_code'], ['code'])
    # ### end Alembic commands ###
